name: Playwright Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Setup
        run: |
          npm run setup
          nohup npm run start:server &
          nohup npm run start:client &
          until curl -s http://localhost:3000/ > /dev/null; do
            sleep 1
          done
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
